language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
  - oraclejdk8

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test

  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -ma,e "ivydata-*.properties" | xargs rm
